### ISSUE TITLE
Intermittent error

### ISSUE THREAD

**Issue by tommaso-borgato** [wildfly-extras/prospero-extras#18]
**Describe the bug**

We have an intermittent issue when running the following merge command:

```
java -jar prospero-extras-1.0.0.Beta5-shaded.jar manifest-merge /tmp/eap8ChannelManifest10178228119131734248.yaml /tmp/xp5ChannelManifest14995532158762293281.yaml     --name=eap-8.0-plus-eap-xp-5.0     --id=eap-8.0-plus-eap-xp-5.0
15:32:36 ": org.wildfly.channel.InvalidChannelMetadataException: Invalid manifest
15:32:36 caused by:
15:32:36  $.streams[151].version: is missing but it is required
15:32:36  $.streams[151].versionPattern: is missing but it is required
15:32:36 
15:32:36 	at org.wildfly.channel.ChannelManifestMapper.from(ChannelManifestMapper.java:100)
15:32:36 	at org.wildfly.prospero.extras.manifest.merge.ManifestMergeCommand.call(ManifestMergeCommand.java:40)
15:32:36 	at org.wildfly.prospero.extras.manifest.merge.ManifestMergeCommand.call(ManifestMergeCommand.java:18)
15:32:36 	at picocli.CommandLine.executeUserObject(CommandLine.java:1953)
15:32:36 	at picocli.CommandLine.access$1300(CommandLine.java:145)
15:32:36 	at picocli.CommandLine$RunLast.executeUserObjectOfLastSubcommandWithSameParent(CommandLine.java:2358)
15:32:36 	at picocli.CommandLine$RunLast.handle(CommandLine.java:2352)
15:32:36 	at picocli.CommandLine$RunLast.handle(CommandLine.java:2314)
15:32:36 	at picocli.CommandLine$AbstractParseResultHandler.execute(CommandLine.java:2179)
15:32:36 	at picocli.CommandLine$RunLast.execute(CommandLine.java:2316)
15:32:36 	at picocli.CommandLine.execute(CommandLine.java:2078)
15:32:36 	at org.wildfly.prospero.extras.Main.main(Main.java:37)
15:32:36 
```

**To Reproduce**
see description

**Expected behavior**
No intermittent error

**Desktop (please complete the following information):**
 - JVM version [e.g. 11.0.20]

**Additional context**

**Comment by spyrkob** [comment]
@tommaso-borgato could you share the manifests you're trying to merge? Based on the error it looks like some fields are not set in those.
